### ISSUE TITLE
Error	 TS17009 'super' must be called before accessing 'this' in the constructor of a derived class.

### ISSUE THREAD

**Issue by mwinkler** [dibiancoj/Linq4Javascript#3]
Hi
Get this error when i try to compile JLinq.ts with TypeScript 1.8 compiler.

**Comment by dibiancoj** [comment]
Hi,
I appreciate you letting me know. I was a little late getting Typescript 1.8 downloaded. It appears they had a breaking change which broke the library. 

The breaking change located here: https://github.com/Microsoft/TypeScript/issues/3876

Grab the latest release https://github.com/dibiancoj/Linq4Javascript/releases/tag/3.0.1 or source code from master and it should be up and running. Let me know if you run into any issues.

Thank you again,
Jason
